### ISSUE TITLE
Collada serializer reactivation

### ISSUE THREAD

**Issue by cacu100** [opensourceBIM/Collada#4]
The collada serializer returns empty files. I found this information on log file
java.lang.NoSuchMethodError: org.bimserver.models.geometry.GeometryData.getIndices()[B
	at org.bimserver.collada.ColladaSerializer.setGeometry(ColladaSerializer.java:220)
	at org.bimserver.collada.ColladaSerializer.writeGeometries(ColladaSerializer.java:204)
	at org.bimserver.collada.ColladaSerializer.write(ColladaSerializer.java:149)
	at org.bimserver.plugins.serializers.EmfSerializer.writeToOutputStream(EmfSerializer.java:106)
	at org.bimserver.plugins.serializers.EmfSerializerDataSource.writeToOutputStream(EmfSerializerDataSource.java:60)
	at org.bimserver.plugins.serializers.CacheStoringEmfSerializerDataSource.writeToOutputStream(CacheStoringEmfSerializerDataSource.java:37)

**Comment by cacu100** [comment]
According with @rubendel suggestion on this information [https://github.com/opensourceBIM/Collada](url) I'm interesting on participate coding to fix this issue on the project. How can I start?.

**Comment by rubendel** [comment]
Always welcome, you can do that by providing pull requests
